### ISSUE TITLE
DNS Won't work

### ISSUE THREAD

**Issue by rjclarkewp007** [ab77/netflix-proxy#9] opened 2015-06-30 19:24 UTC
HI

Was wondering if you could help me.
I setup a new Ubuntu instance, assigned the floating IP and set the firewall rule.
Ran the command as per your instructions.
Set my DNS to the floating IP on my PC and for some reason I just can't get any internet and obviously also no netflix!

Am I missing something here?
It's like the instance is not allowing DNS port 53 to route through it or something.

**Comment by ab77** [comment] 2015-07-01 07:35
Hi there, I am guessing by the terminology you are using (floating IP),
that you are having issue with DreamCompute?

-- ab1

**Comment by rjclarkewp007** [comment] 2015-07-01 07:58
Hi Anton

 

Yes, that is correct. I’ve done everything as per the guide, but as soon as I change my DNS to the IP of DreamCompute instance I have no internet.

 

Strange thing is that it worked for a while and then I tested on another computer which is on a different network. That did not work. So I rebooted my router (which was working at the time) and after the reboot mine also did not work anymore.

 

What I’m I doing wrong here?

Thanks for the help!! Really appreciate it very much!

 

Raymond Clarke

Mobile: 071 480 6651

Mail Address:  <mailto:rjclarkewp007@gmail.com> rjclarkewp007@gmail.com

**Comment by ab77** [comment] 2015-07-01 08:28
Hi there, there was actually an issue with the build script running in a non-root environment.

I've now fixed the issue, so could you please try again from scratch after removing/terminating your existing DreamCompute instance. 

Having said all that, I do recommend you use DigicalOcean though, it is a bit faster and easier overall :)

-- ab1

**Comment by rjclarkewp007** [comment] 2015-07-01 09:04
Thanks Anton

 

It does seem to work now. I actually used DigitalOcean first and it worked, but then found that Hulu keeps saying this:

 



 

So I though let’s try DreamCompute, but I see it still says this. Netflix work fine though.

 

Is there any way around this?

 

Thanks again!!

 

Raymond Clarke

Mobile: 071 480 6651

Mail Address:  <mailto:rjclarkewp007@gmail.com> rjclarkewp007@gmail.com

**Comment by ab77** [comment] 2015-07-01 09:10
Great, at least it builds now :)

Now regarding Hulu.. They are very aggressive in blocking IP ranges for
known cloud/VPN/proxy providers.

I've had success previously in the past with DreamCompute. Linode and
DigitalOcean , but lately none of them work for Hulu.

You could try an Amazon EC2 instance. It is more expensive, but uses
similar instructions to DreamCompute. You'll need to alter the build
command to use a different user name (e.g. ec2-user or ubuntu-user, etc.).

Hope this helps!

Please close the issue if this resolves your problem..

-- ab1

**Comment by rjclarkewp007** [comment] 2015-07-01 09:12
Thank you so much! I will do so!

 

Raymond Clarke

Mobile: 071 480 6651

Mail Address:  <mailto:rjclarkewp007@gmail.com> rjclarkewp007@gmail.com

**Comment by rjclarkewp007** [comment] 2015-07-01 09:31
Sorry Anton, just a quick question. Please don’t feel obligated to answer this though.

I wanted to know if there is any way to make sure only me and 3 other people can use this DNS. So is there a way that I can set it up so that it will only except certain MAC addresses? As our public IP will always change so we can’t blocked it that way.

 

I’m just worried my friends will start giving out the IP to everyone and I don’t want that happening. :)

 

Raymond Clarke

Mobile: 071 480 6651

Mail Address:  <mailto:rjclarkewp007@gmail.com> rjclarkewp007@gmail.com

**Comment by ab77** [comment] 2015-07-01 10:11
So `MAC` addresses are no good to you, since they operate at a different network layer (see [OSI model](https://en.wikipedia.org/wiki/OSI_model)).

What you actually want to do, is to get all your friends to configure a dynamic `DNS` host, which they manually or automatically update when their IP address changes. You can use something like [No-IP](http://www.noip.com/) for this.

For this example, let's assume your dynamic hosts are:
* my-dynamic-hostname.no-ip.org (this is yours)
* my-friend-hostname.no-ip.org (this is your friend's dynamic hostname)
* my-other-friend-hostname.no-ip.org (this is your other friend's dynamic hostname)

Once you have your dynamic hosts setup, you'll need to make some changes to your `iptables` rules, create a script on your VPS and schedule it to run via cron.

Your `etc/iptables.rules` will currently look like this:

    # Generated by iptables-save v1.* on Tue Apr 21 05:30:50 2015
    *filter
    :INPUT ACCEPT [0:0]
    :FORWARD ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    :DOCKER - [0:0]
    ...
    -A INPUT -s your_ip_address/32 -p tcp -m tcp --dport 80 -j ACCEPT
    -A INPUT -s your_ip_address/32 -p tcp -m tcp --dport 443 -j ACCEPT
    ...
    -A DOCKER -s your_ip_address/32 -p udp -m udp --dport 53 -j ACCEPT
    ...

They will need to be modified as follows:

    # Generated by iptables-save v1.* on Tue Apr 21 05:30:50 2015
    *filter
    :INPUT ACCEPT [0:0]
    :FORWARD ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    :DOCKER - [0:0]
    ...
    -A INPUT -s my-dynamic-hostname.no-ip.org -p tcp -m tcp --dport 80 -j ACCEPT
    -A INPUT -s my-dynamic-hostname.no-ip.org -m tcp --dport 443 -j ACCEPT
    -A INPUT -s my-friend-hostname.no-ip.org -p tcp -m tcp --dport 80 -j ACCEPT
    -A INPUT -s my-friend-hostname.no-ip.org -p tcp -m tcp --dport 443 -j ACCEPT
    -A INPUT -s my-other-friend-hostname.no-ip.org -p tcp -m tcp --dport 80 -j ACCEPT
    -A INPUT -s my-other-friend-hostname.no-ip.org -p tcp -m tcp --dport 443 -j ACCEPT
    ...
    -A DOCKER -s my-dynamic-hostname.no-ip.org -p udp -m udp --dport 53 -j ACCEPT
    -A DOCKER -s my-friend-hostname.no-ip.org -p udp -m udp --dport 53 -j ACCEPT
    -A DOCKER -s my-other-friend-hostname.no-ip.org -p udp -m udp --dport 53 -j ACCEPT
    ...

Next, here is the script I modified a little from [here](https://wiki.gutzmann.com/confluence/display/HowTo/IPTables+Firewall+Setup+for+Dynamic+DNS):

    #!/usr/bin/perl -w
    # restart the firewall if the IP address changed
    # /etc/sysconfig/iptables
    use strict;

    pAllow("my-dynamic-hostname.no-ip.org");
    pAllow("my-friend-hostname.no-ip.org");
    pAllow("my-other-friend-hostname.no-ip.org");

    sub pAllow {
      my ($aName) = @_;
      #print "aName: $aName\n";
      my $vAddress = readpipe("host $aName | cut -d \" \" -f4");
      chomp $vAddress;
      #print "vAdress: $vAddress\n";
      my $vName = readpipe("host $vAddress | cut -d \" \" -f5");
      chomp $vName;
      if ($vName =~ "SERVFAIL") {
        $vName = $vAddress;
      }
      #print "vName: $vName \n";
      if ($vName ne "") {
        if (system("/sbin/iptables -L -v | grep -i $vName > /dev/null ") != 0) {
          system "/sbin/iptables-restore/iptables-restore < /etc/iptables.rules" ;
          system "/usr/bin/docker restart bind sniproxy" ;
        }
      }
    }

Save it to `/opt/scripts` and schedule it to run every 15 minutes like this:

    # crontab -e

    */15 * * * * /opt/scripts/update-firewall.pl


Hope this helps, let me know how it goes..

-- ab1

**Comment by rjclarkewp007** [comment] 2015-07-01 10:50
Thanks Anton, I will check it out for sure!

 

I see this DNS thing is still doing the same thing.

So it worked on my laptop until i rebooted the modem. So the Public IP changed, that all as far as I know that changed. Since then the DNS won’t work. No internet at all.

 

Also, if I try it on any other PC outside my network there is also no internet at all.

 

Any ideas?

 

Raymond Clarke

Mobile: 071 480 6651

Mail Address:  <mailto:rjclarkewp007@gmail.com> rjclarkewp007@gmail.com

**Comment by ab77** [comment] 2015-07-01 10:57
You'll need to switch to using dynamic DNS host in your `iptables` rules and have your modem automatically update it.

It won't work outside your network by design, since `iptables` firewall blocks all IPs outside your network. Otherwise you'll have an open DNS resolver on the Internet, which is really, (**really**) bad.

**Closed by ab77** 2015-07-01 10:57 UTC
