### ISSUE TITLE
netflix-proxy stopped working

### ISSUE THREAD

**Issue by 1f5** [ab77/netflix-proxy#180] opened 2016-06-02 01:14 UTC
netflix-proxy worked really great for me, but stopped working today.
I now get the Streaming Proxy Error even when i try to watch Series/Episode that should be available in my Region. My VPS Provider is RamNode. Still no luck after reinstalling netflix-proxy completely and trying other Tunnel Endpoints and other Server Providers and Locations.
Seems like Netflix is using a new Method to detect netflix-proxy. Please look into it.

**Comment by 3djake** [comment] 2016-06-02 04:05
yeah, they may be blocking the HE endpoints.

**Comment by kyle95wm** [comment] 2016-06-02 04:21
I too can confirm this. rip

**Comment by kyle95wm** [comment] 2016-06-02 04:28
Alright so I took down the server on my end. Guess I'll have to either wait for there to be a fix here, or go for a third party like GetFlix or Unlocator since those two seemed to have worked in the past.

**Comment by 3djake** [comment] 2016-06-02 04:30
I am testing vultr now, was using DigitalOcean and it worked great up until today

**Comment by kyle95wm** [comment] 2016-06-02 04:42
Trust me, don't even try. The ENDPOINTS on HE's end are blocked. They'd need new addressing to bypass this minor inconvenience.

**Comment by kyle95wm** [comment] 2016-06-02 05:10
Any updates? A friend of mine is using Hola

**Comment by 3djake** [comment] 2016-06-02 05:22
getflix is working via browser but does not work for other devices even if you are routing all port 53 traffic using DNSMasq, which should work.
iptables -t nat -A PREROUTING -i br0 -p udp --dport 53 -j DNAT --to 10.0.0.1
iptables -t nat -A PREROUTING -i br0 -p tcp --dport 53 -j DNAT --to 10.0.0.1

**Comment by ab77** [comment] 2016-06-02 06:41
Yep, confirmed. They've started blocking HE as well as some other IPv6 ranges. Party over.

**Comment by kyle95wm** [comment] 2016-06-02 07:18
For now…

**Comment by yellow1912** [comment] 2016-06-02 13:50
Getflix is working for now (only 2 of their dns tho), too sad this does not work anymore.

**Comment by renevaughannz** [comment] 2016-06-02 18:35
Mine stopped working too! This is terrible news. Does anyone see a solution for this, anytime soon?

**Comment by zippoxer** [comment] 2016-06-02 19:23
If they blocked HE endpoints, can't we host our own tunnels?

**Comment by boogies** [comment] 2016-06-02 20:35
I hope you would figure out how to fix it. But anyway, thank you for sharing such a  great solution so far.

**Comment by ab77** [comment] 2016-06-02 20:47
@zippoxer: If you have a router that can establish a tunnel to HE, you can try. I have an old London tunnel, which I use for my IPv6 connectivity from to firewall at home and it gives me UK Netflix. I've not tried to switch it to another (US) tunnel endpoint to see what would happen.

**Comment by kyle95wm** [comment] 2016-06-02 21:35
I hope theres a reliable solution for this soon. Im missing my daily dose of US Netflix

**Comment by cdhowie** [comment] 2016-06-03 02:28
I have written [a DNS proxy](https://gist.github.com/cdhowie/c38d5651f2cb150bf37cb449d147eb3f) that returns empty results for any AAAA query to netflix.com or a subdomain thereof and passes everything else onto a local resolver on port 10053 (which I've configured dnsmasq to listen on).  The result of this is that systems on my network cannot dig any AAAA records for Netflix, and therefore use IPv4 for it instead.  Leaving this here in the hopes that it will be useful to others.

**Comment by cdhowie** [comment] 2016-06-03 02:34
I have written [a DNS proxy](https://gist.github.com/cdhowie/c38d5651f2cb150bf37cb449d147eb3f) that returns empty results for any AAAA query to netflix.com or a subdomain thereof and passes everything else onto a local resolver on port 10053 (which I've configured dnsmasq to listen on).  The result of this is that systems on my network cannot dig any AAAA records for Netflix, and therefore use IPv4 for it instead.  Leaving this here in the hopes that it will be useful to others.

(Cross-posted to /r/ipv6 too.)

**Comment by kyle95wm** [comment] 2016-06-03 07:04
Im still not getting the point of this @cdhowie

**Comment by svempa434** [comment] 2016-06-03 09:29
@cdhowie: Thanks, that solves my problem.

**Comment by lbdroid** [comment] 2016-06-03 13:13
Well, they definitely did *something* a couple of days ago, and it wasn't *limited* to adding a few IP addresses to their blacklist. My endpoint was NOT blacklisted, but still failing. What I found in a tcpdump from my router, was that there were some connections from my chromecast to netflix owned IP addresses, but **NO** corresponding DNS lookups. Even after forcing those IP addresses to a sni proxy, still no luck, since apparently the requests didn't include hostnames. I ended up having to add those addresses to my routing table. Ultimately, its a better solution than proxying anyway.

**Comment by ab77** [comment] 2016-06-03 13:18
So did you get it working again?

**Comment by lbdroid** [comment] 2016-06-03 13:25
Like I said, once the ip addresses were added to the routing table and tunneled to the endpoint instead of being proxied through it.

**Comment by cdhowie** [comment] 2016-06-03 13:27
@kyle95wm If you are using HE to bypass geo restrictions then my DNS proxy won't be of any use to you.  If you are an HE user who finds yourself unable to watch Netflix due to them blocking HE tunnels, but you *could* watch over your IPv4 connection if Netflix were to use it, then my DNS proxy will fix the problem by simply hiding all of the Netflix AAAA records and thereby forcing Netflix to use IPv4.

**Comment by ab77** [comment] 2016-06-03 13:33
@lbdroid what IP addresses? I am interested to understand how you got it working and also how you've managed to keep you tunnel going, without being blocked like everyone else...

@cdhowie you know you can just set  [mode ipv4_only](https://github.com/dlundquist/sniproxy/blob/master/sniproxy.conf) in `sniproxy.conf` to achieve the same thing?

**Comment by lbdroid** [comment] 2016-06-03 14:03
@ab77 : there are a number of ways to do it. I haven't finished narrowing it down entirely just yet, but in theory, you should be able to route everything in AS2906 by "route add" to a tun device and call it a day. Or, if you are using dedicated devices that can be setup to route everything, a source based routing policy should be able to say if the request comes from device with this IP address, feed it out through the tun device, otherwise feed it out through the default gateway.

Source based routing actually adds a lot of flexibility, since it gives you the option of using multiple netflix catalogs at the same time from different devices.

You could even use a combination of the two. So source based policy that feeds AS2906 addresses to the tun, but everything else to the default gateway.

And for extra points, run a php script on the router that gives you a dropdown to select which tunnel to use.

So easy way to set up the tunnel, is OpenVPN, or SSH (use autossh, since ssh alone can fall apart after a while). OpenWRT has OpenVPN packages, and easily handles the fancy routing. EVERY linux distro also has everything needed.

As far as keeping my endpoint from being blacklisted, there is an advantage to owning property in the US ;)

**Comment by ab77** [comment] 2016-06-03 14:08
> As far as keeping my endpoint from being blacklisted, there is an advantage to owning property in the US ;)

OK, now I understand. Maybe you get a reasonably sized server, deploy the proxy on it and give me the IP?  :grimacing:

**Comment by lbdroid** [comment] 2016-06-03 15:57
I'll leave this here for anybody who might find it useful;

for net in `whois -h whois.radb.net -- '-i origin AS2906' | grep "route: " | awk '{print $NF}' | sort | ./listclean.sh`; do route add -net $net dev tun0; done

where listclean.sh is;
```
#!/bin/bash -i

func0(){
	local s e i
	for i in ${!u[@]}
	do
		[ $1 -ge $[i+1] ]&&[ $1 -le $[u[i]+1] ]&&s=$i
		[ $2 -ge $[i-1] ]&&[ $2 -le $[u[i]-1] ]&&e=$i
	done

	if [ "$s" ]
	then
		if [ "$e" ]
		then
			[ $s -ne $e ] && {
				u[s]=${u[e]}
				unset u[e]
			}
		else
			[ $1 -lt $s ] && {
				u[$1]=${u[s]}
				unset u[s]
				s=$1
			}
			[ $2 -gt ${u[s]} ] && u[s]=$2
		fi
	else
		if [ "$e" ]
		then
			[ $1 -lt $e ]&&{ u[$1]=${u[e]}
				unset u[e]
				e=$1
			}
			[ $2 -gt ${u[e]} ] && u[e]=$2
		else
			u[$1]=$2
		fi
	fi
}

func1(){ 
	local s=${1#*/} m=${1%/*} z
	[ -z "${s//*.*}" ]&&s=32
	printuint $s z
	set -- ${m//./ }
	m=$[$1<<24|$2<<16|$3<<8|$4]
	func0 $[m&z] $[m|((2**32-1)^z)]
}

printuint(){
	printf -v $2 "%u" $[ (2**32-1)^(~0^~0<<(32-$1))]
}

printstring(){
	printf -v $2 "%s" $[$1>>24].$[$1>>16&255].$[$1>>8&255].$[$1&255]
}

func2(){
	local s z
	while [ "$1" ]
	do
		s=32
		while printuint $[s-1] z&&[ $1 = $[($1>>(33-s))<<(33-s)] ]&&[ $2 -ge $[$1|((2**32-1)^z)] ]
		do
			((s--))
		done
		printstring $1 x
		echo $x/$s
		printuint $s z
		if [ $2 -gt $[$1|((2**32-1)^z)] ]
		then
			set -- $[1+($1|((2**32-1)^z))] $2
		else
			shift 2
		fi
	done
}

while read w
do
	func1 $w
done
p=-1
for o in ${!u[@]}
do
	[ $o -gt $p ] && p=${u[o]} && func2 $o ${u[o]}
done
```

**Comment by kalenjin** [comment] 2016-06-04 21:17
I get a list of IP addresses....what do I then do with them?

**Comment by elbow** [comment] 2016-06-05 17:19
Hi,

Looks like Netflix (and iPlayer) found me too.

@lbdroid thanks for the suggestion to just tunnel the traffic.  And thanks for the script (impressive bash-ing!).

I used GRE tunnels to my Digital Ocean instances. (I have one in the US and one in the UK).
For Netflix AS2906 - routes as found using your whois and listclean.sh.

Unfortunately Netflix still seems to know I'm unblocking.  Perhaps my IP is now on a blacklist.

Kinda fed-up with the hassle, but at the same time not willing to pay the same price for 1/3rd the content - actually in terms of earning power much more than "the same price".  So I think I will just cancel my subscription and keep my $10.

**Comment by ab77** [comment] 2016-06-05 17:41
@elbow: wise move!

**Comment by zippoxer** [comment] 2016-06-05 17:46
I ended up using GetFlix. Works flawlessly, but at a cost :(

**Comment by kyle95wm** [comment] 2016-06-05 23:34
So, is there a way to use GetFlix on a SMART TV for instance? Do we just have to run a DNS server using dnsmasq or something? I'm a little unclear about what was posted above.

**Comment by zippoxer** [comment] 2016-06-05 23:36
GetFlix gives me an address for their DNS server, and similarly to netflix-proxy I just adjust my machine to use that DNS.

**Comment by kyle95wm** [comment] 2016-06-06 01:28
So then does this mean we can use our TV's and consoles as long as things are being passed through a computer?

**Comment by WeirdG** [comment] 2016-06-06 07:54
I found this.  Hope it helps.
https://gist.github.com/cdhowie/

**Comment by lbdroid** [comment] 2016-06-06 13:44
I think we need to clear up a few things;

1) Netflix is employing multiple techniques simultaneously. I think that their "direct-to-IP" isn't fully rolled out yet. Some people seem to be subjected to it, and others not. Since netflix is available on so many platforms with so many variations, there really is no telling if you are subject to it without doing a tcpdump on your router. IP address blacklisting is another approach that they *have not stopped*.

If you happen to be hit with BOTH, then you need to fix BOTH. So routing through a blacklisted endpoint, by ANY means, is not going to fix the problem.

I find that for debugging purposes, it can be very useful to have a means to tunnel *ALL* traffic from your network through the endpoint. This is a quick way to determine if you are being hit by IP blacklisting, or something else. For instance, if you are able to run a VPN server on the endpoint (l2tp, openvpn, ssh, etc.), just set that as your default route and see if netflix starts working. If not, then you are dealing with IP address blacklisting. The nice thing about using a secured tunnel, is that it becomes trivial to control access to it.

2) Over the last couple of days, I've played with it a little bit more. My solution above is incomplete. When I tunnel precisely all of and only the AS2906 addresses, it detects proxying. This is because *.netflix.com is being routed through IP addresses that are allocated to AMAZON AWS.

Which leaves two solutions; either proxying *everything* for those devices on your network connecting to netflix, OR, using a hybrid between netflix-proxy and tunneling AS2906. I *am* trying to build up a non-hybrid solution, and have considered a number of angles;

a) Triggering routing table updates from DNS,
b) Routing all AWS IP's,
c) This one is the most complex, but also the most interesting; this is local hybridized, in which the sniproxy runs *locally* (instead of on a VPS). The local DNS will feed the client with IP's on a local subnet to sniproxy, and the local routing table will take all outbound traffic from sniproxy and feed it through the tunnel.

**Comment by lbdroid** [comment] 2016-06-06 16:18
@WeirdG : look up several posts in this thread ;)

**Comment by lbdroid** [comment] 2016-06-06 16:37
There is another AS block assigned to netflix.... AS394406, so that would have to be done in addition to AS2906. This seems to be used for nflximg.com. I'm not aware of any geoblocking on it though (yet).

**Comment by WeirdG** [comment] 2016-06-06 16:42
BTW... DNS Trick works, and they offer a 14-day free trial.

**Comment by lbdroid** [comment] 2016-06-06 17:52
Note: if you just want to say "to hell with it", you could add AS14618 along with AS2906 and AS394406, and every possible IP address that netflix will geoblock, will be sent through the tunnel. How efficient this is, is dependent on how much of your non-netflix traffic ends up at amazon aws, since it will dump all the aws traffic through the tunnel in addition to all the netflix.

**Comment by lbdroid** [comment] 2016-06-07 03:52
Got it working with OpenWRT!!!

Add following to /etc/config/firewall:
```
config ipset                                 
    option name 'domain-filter-ipv4'            
    option match 'dest_ip'                      
    option storage 'hash'                    
    option family 'IPv4'                        
                                                
config rule                                  
    option src 'lan'                            
    option target 'MARK'                        
    option set_mark '0x1'                    
    option name 'Tag Domain Filter Traffic'     
    option family 'IPv4'                        
    option ipset 'domain-filter-ipv4'        
    option proto 'tcp udp icmp'
```

contents of /etc/config/ipset-dns:
```
config ipset-dns
	# use given ipset for type A (IPv4) responses
	option ipset 'domain-filter-ipv4'

	# use given ipset for type AAAA (IPv6) responses
	option ipset6 'domain-filter-ipv6'

	# use given listening port
	# defaults to 53000 + instance number
	option port  '53001'

	# use given upstream DNS server,
	# defaults to first entry in /tmp/resolv.conf.auto
	option dns   '8.8.8.8'
```

dnsmasq.conf:
```
server=/netflix.net/netflix.com/nflxvideo.net/nflxvideo.com/nflximg.net/nflximg.com/127.0.0.1#53001
```

Add line to /etc/iproute2/rt_tables:
```
248	nftable
```

Add to /etc/rc.local:
```
/usr/sbin/openvpn --route-noexec --route-up /etc/nfroutes.sh --script-security 2 --route-pre-down /etc/nfdownroutes.sh --config /etc/openvpn/usa.ovpn &
ip rule add fwmark 0x1 table nftable priority 1000
```

contents of nfroutes.sh:
```
#!/bin/sh
 
gw=`ifconfig | grep -A1 tun0 | grep "P-t-P" | cut -d\: -f3 | cut -d\  -f1`

for net in 23.246.0.0/18 37.77.184.0/21 45.57.0.0/17 64.120.128.0/17 66.197.128.0/17 69.53.224.0/19 108.175.32.0/20 185.2.220.0/22 185.9.188.0/22 192.173.64.0/18 198.38.96.0/19 198.45.48.0/20 208.75.76.0/22
do
	route add -net $net gw $gw metric 1
done

ip route add default via $gw table nftable
```

contents of nfdownroutes.sh:
```
#!/bin/sh
 
gw=`ifconfig | grep -A1 tun0 | grep "P-t-P" | cut -d\: -f3 | cut -d\  -f1`

for net in 23.246.0.0/18 37.77.184.0/21 45.57.0.0/17 64.120.128.0/17 66.197.128.0/17 69.53.224.0/19 108.175.32.0/20 185.2.220.0/22 185.9.188.0/22 192.173.64.0/18 198.38.96.0/19 198.45.48.0/20 208.75.76.0/22
do
	route del -net $net gw $gw metric 1
done

ip route del default via $gw table nftable
```

**Comment by lbdroid** [comment] 2016-06-07 13:12
Hmm, one more thing that I could do to make this just a little bit more... slick. Switching out in config ipset from match dest_ip to dest_net, then instead of adding to the main routing table, add all AS2906 networks to the ipset.

Then we can (but I'm not going to myself, I'll leave that for someone else) use iptables to set different marks based on the source IPs and add multiple additional routing tables for those different marks. This would allow us to have multiple tunnels and "pick and choose" which devices route through which tunnel. Throw in a little php script that lets you select a tunnel for the device that you are connecting from (as well as optionally tying another device, like one of your chromecasts to it) and having it update the iptables rules... and $$profit$$.

**Comment by poutinefb** [comment] 2016-06-08 10:46
ibdroid, first of all many thanks for sorting this out!

 I am just wondering if OpenWRT uses optware or entware.

I am on AsusMerlin with entware.  So the packages are slightly different.  For example, ipset is ipsetv4 and ip is ip-legacy (but both give ipset and ip after intalling, which are in /opt/sbin).  The usage for ipset-dns is different (it goes: ipset-dns ipv4-ipset ipv6-ipset port upstream). So it makes me wonder if the config ipset-dns is necessary. Also, some things are different like /etc/config/firewall or /etc/config/network etc. do not exist, dnsmas.conf is in /etc and I cannot find rc.local.

I am kind of stuck here.  Any advice?

**Comment by 3djake** [comment] 2016-06-08 11:14
I think OpenWRT uses OPKG/entware and dd-wrt uses optware.

**Comment by lbdroid** [comment] 2016-06-08 13:47
@poutinefb : I'm not quite sure if you understand how this works... ipset-dns is used to populate the ipset based on DNS query results -- since *.netflix.com uses AMAZON ip addresses, the only way to prepopulate that would be to add ALL of Amazon (AS14618), which is undesirable for performance reasons. iptables compares the destination ip addresses for all outbound packets to the networks and ip addresses in the ipset. If it matches, it tags the packet with "0x1" and sends it on its way. The next stop is the routing system, which looks at incoming packets and checks if it has the 0x1 tag or not and uses that tag to select which routing table to use for it. Our special routing table has just one entry, which is a default route that feeds everything over the tunnel interface.

So EVERY time some device does a DNS lookup for *.netflix.com, that query is forwarded by dnsmasq to ipset-dns, which forwards the request to 8.8.8.8. ipset-dns reads the response while forwarding it back to dnsmasq, and adds the IP addresses in the response to the ipset.

IF the dnsmasq that comes with your distro has ipset support compiled in, then you can leave out ipset-dns, since the job can be done by dnsmasq directly.

entware was developed *for* openwrt. Think of it like RPM (package manager developed for RedHat). It does not mean that the package names are the same, and it does not mean that they are the same versions, and it does not mean that they are compiled with the same options.

Looks to me like you are using a "light mod" firmware addon? Or possibly a rebuild based on the factory source code. I won't be able to help you much sorting out the distinctions.

**Comment by lbdroid** [comment] 2016-06-08 15:06
Oh, actually... looks like there are multiple variants of dnsmasq available through openwrt repos. One of them is dnsmasq-full, which includes ipset and ipv6.

opkg remove dnsmasq
opkg install dnsmasq-full
opkg remove ipset-dns

instead of server=/netflix.com/127.0.0.1#53001 in the dnsmasq.conf, use
ipset=/netflix.com/domain-filter-ipv4

**Comment by poutinefb** [comment] 2016-06-09 01:16
ibdroid, thanks for the information.  This is a really dumb question but it seems rt_tables is read only.  Is that normal???

**Comment by 3djake** [comment] 2016-06-09 02:00
That does not sound normal, are you sure you tried changing it as root?

**Comment by lbdroid** [comment] 2016-06-09 03:53
@poutinefb it is just a file, so check its permissions and check how it's filesystem is mounted. If all else fails, you don't actually need to modify that file at all, instead, just address the routing table by number.

**Comment by poutinefb** [comment] 2016-06-09 13:03
@lbdroid Thanks for your time and patience.  It is really appreciated.  I managed to get around my previous problem.  Despite the differences with my router, I was able to get through the different steps.  That being said,  it doesn't work (I am not surprised). I am wondering if something needs to be activated or should it start automagically?

**Comment by lbdroid** [comment] 2016-06-09 14:36
Ok, well start by checking your ipsets with command "ipset list",

dump your routing rule list "ip rule list",

dump all your routing tables with "for table in `ip rule list | awk '/lookup/ {print $NF}'`; do echo "TABLE: $table"; ip route list table $table; done",

dump your mangle table with "iptables -t mangle --list" and "ip6tables -t mangle --list"


Are you using ipv6, ipv4, or both?

**Comment by ab77** [comment] 2016-06-10 11:29
@lbdroid - very elegant solution in https://github.com/ab77/netflix-proxy/issues/180#issuecomment-224166147, thank you!

Just managed to read through and internalise. I've not tried it yet, but if you got it working under Open WRT, any half-decent Linux distro should be able to handle it. 😬 

My only question is around routing of the entire AS. Is that to make sure that if Netflix apps hardcode media server IPs internally, they are routed correctly anyway?

Otherwise you could just have a second `dnsmasq` ipset:
`ipset=/nflxvideo.net/domain-filter-ipv4,domain-filter-ipv6`


-- ab1

**Comment by lbdroid** [comment] 2016-06-10 13:18
Correct. It easily deals with hardcoded IP's, or IP's delivered via HTTP.
In addition, adding networks to the ipset where possibly, rather than IP's, keeps the ipset smaller than it could otherwise get.

**Comment by ab77** [comment] 2016-06-10 13:24
@lbdroid Very good. Once I find a donor in the USA to host a RPi or similar for me, I will experiment 😬

**Comment by ab77** [comment] 2016-06-28 23:03
@lbdroid OK, got this all going between a couple of boxes. 

> Update: I've taken some measures to address ipv6, but haven't tested it, since I don't have ipv6.

I can confirm IPv6 works with this configuration.

**Comment by lbdroid** [comment] 2016-06-29 13:01
Glad to hear that you were able to reproduce it. Excellent to know that the IPv6 is working, thank you!

**Comment by markcodes** [comment] 2016-07-03 09:50
hi @lbdroid

can you convert your ipset rules and network rules to ubuntu 14?

thank you. much appreciated

**Comment by lbdroid** [comment] 2016-07-04 12:57
No. I have fully explained all of the concepts and mechanisms at work, so feel free to implement it on whatever distribution you prefer.

**Comment by markcodes** [comment] 2016-07-05 09:39
can anyone please..

**Comment by dimatr** [comment] 2016-07-21 12:21
hi @lbdroid

First of all many thanks for the elegant and working solution! I need a hint on solving one riddle. In short: for *some* OpenVPN setup the *.nflxvideo.net and *netflix.com is not reachable from wifi/ethernet clients behind the OpenWRT router. Here are more details.

this server is used as a test one for ping and other tools: 
ipv4_1-cxl0-c039.1.dus001.ix.nflxvideo.net (198.38.119.148)


* OpenWRT Chaos Calmer, nothing fancy installed or configured
* I have an OpenVZ server in the US, installed OpenVPN there, standard server.conf, TAP interface type
* When I configure OpenVPN client NOT to use nfroute.sh and nfdownroute.sh, then after connecting the ping and traceroute are happy with the test .nflxvideo.net server. All the traffic goes from wifi client through OpenVPN def1, this can be confirmed with traceroute. But then of course Netflix complains "Oops, you are using proxy/vpn"
* When I configure OpenVPN client to use nfroute.sh and nfdownroute.sh, then after connecting the wifi client cannot ping the test server anymore. Destination unreachable. The "arp" command shows the 198.38.119.148 with fwmark 0x1 (good, the rule is applied) but 00:00:00:00:00 as HWaddress (bad, the IP could not be discovered). Other IPs/sites are pingable and usable just fine.

The two tests suggest there's something with the table setup / missing route / something else.


* Using completely another [preconfigured] OpenVPN instance everything is fine, the whole setup works, Netflix does not complain, "arp" shows many IPs with non-zero tap0 HWaddress. I do not have a grip on this OpenVPN server, can only use one.

I could not guess the difference between the two cases, thus asking for the debug hints. 
* what tools to use to narrow the problem down? What could be the problem at all knowing the two scenario above?
* nameserver issue?  DHCP is configured for using 8.8.8.8 and 8.8.4.4. I have tried 4.4.2.1 and 4.4.2.2 - same behavior.
* OpenVZ peculiarities?  Other IPs/sites work fine on wifi clients, traceroute shows the first hop to OpenWRT and the second hop to tap0 subnet == the traffic is redirected properly.
* other things? TAP vs TUN?

many thanks for the help!

**Comment by kyle95wm** [comment] 2016-10-09 21:46
IS this going anywhere?

**Comment by ab77** [comment] 2016-10-10 05:57
Please register for updates on the mailing list (http://netflix-proxy.belodedenko.me/) RE: August update. An alternative (paid subscription based) unblocking solution is close to being completed and should be going to trial soon.

**Closed by ab77** 2016-10-10 05:57 UTC
