### ISSUE TITLE
Update not working? 

### ISSUE THREAD

**Issue by nixxle** [ab77/netflix-proxy#112] opened 2016-03-24 20:17 UTC
I'm trying your new update, using the tunnel broker. I have no idea what that is, but I did as you say in the readme and after installation everythinig seems fine on the server. 

But on the netflix site, I get "Internet Connection Problem", which is good, because it doesn't say " Proxy error" anymore. 

I devtools, I see a lot of calls to 
https://ipv6_1-lagg0-c068.1.iad001.ix.nflxvideo.net/range/0-18101?..

timing out.

Also, you should probably set something like this up as some kind of paid service :)

**Comment by ab77** [comment] 2016-03-25 09:14
Try rebuilding on another VPS (destroy your current one).

Otherwise, see if you can troubleshoot from the command line first..

```
dig ipv6_1-lagg0-c068.1.iad001.ix.nflxvideo.net @<your-vps-ip>
curl -v -H 'host: ipv6_1-lagg0-c068.1.iad001.ix.nflxvideo.net' <your-vps-ip>
```

**Comment by scottaki** [comment] 2016-03-25 11:25
I'm having the same issues here too @nixxle – everything seems to check out, and both of those two tests seem to return positive results @ab77. It's working on DO though it seems? Must be a configuration issue of some kind then... Maybe I should spin up an instance there and see if that makes any difference. Just liking my current VPS provider, is all, but not much use if the actual end result isn't positive.

**Comment by ab77** [comment] 2016-03-25 11:27
What provider are you using? I am happy to test it out..

**Comment by timmyj** [comment] 2016-03-25 11:38
same issue here on vultr, tried debian/ubuntu hosts

**Comment by scottaki** [comment] 2016-03-25 11:40
Just confirming – we should be configuring VPS to be without IPv6 support now, or still with support just no local addresses configured? If I build without IPv6, and the `build.sh` script says `IPV6=Disabled`, the system seems to work and the error disappears... but Netflix comes back with proxy detected instead.

**Comment by scottaki** [comment] 2016-03-25 11:50
Just built from scratch with a new DO droplet – same error. Seems like it might be an issue with the code or perhaps the hurricane tunnel? I'm leaning towards the tunnel, as everything was working before that change was required. Perhaps we're missing something at that end? (Or perhaps they've made a move to block this traffic?)

**Comment by ab77** [comment] 2016-03-25 12:14
I just tested on Vultr and it works fine for me.

If you get `IPv6=Disabled`, then your tunnel isn't working. After you modify your interfaces files and before you try to deploy the proxy, just run `ifup he-ipv6`, followed by `ping6 google.com`.

If you get no reply, don't go any further until you've got the tunnel working. Don't build your server with Vultr IPv6 option, make sure it is IPv4 only.

**Comment by scottaki** [comment] 2016-03-25 12:16
How strange... problem, at least for me, is that it appears to work...

```
ping6 google.com
PING google.com(lax17s03-in-x0e.1e100.net) 56 data bytes
64 bytes from lax17s03-in-x0e.1e100.net: icmp_seq=1 ttl=58 time=1.01 ms
64 bytes from lax17s03-in-x0e.1e100.net: icmp_seq=2 ttl=58 time=1.15 ms
64 bytes from lax17s03-in-x0e.1e100.net: icmp_seq=3 ttl=58 time=1.07 ms
64 bytes from lax17s03-in-x0e.1e100.net: icmp_seq=4 ttl=58 time=1.07 ms
```

Everything, that is, except for actual streaming of content.

**Comment by ab77** [comment] 2016-03-25 12:20
Try DO maybe to rule out an issue with your local network setup?

**Comment by scottaki** [comment] 2016-03-25 12:22
Yep, did already. Same issue as the original post and my current non-DO setup. Netflix just reported "internet connection problem".

**Comment by ab77** [comment] 2016-03-25 12:23
Sorry, no idea. Give me access to your server and I'll have a look to see if I can work it out..

**Comment by scottaki** [comment] 2016-03-25 12:23
I'll spin that DO droplet back up and you can jump in!

**Comment by abukabhs** [comment] 2016-03-25 12:33
I am using digitalocean and facing the following issues:
sudo iptables -I FRIENDS -s x.x.x.x/32 -j ACCEPT iptables-save > /etc/iptables/rules.v4 || iptables-save > /etc/iptables.rules
it adds 3 lines ip addresses of my VPS

And it doesn't delete ip addresses when I run
sudo iptables -D FRIENDS -s x.x.x.x/32 -j ACCEPT iptables-save > /etc/iptables/rules.v4 || iptables-save > /etc/iptables.rules

I also receive Bad Argument 'Iptables-save'

**Comment by ab77** [comment] 2016-03-25 12:34
@abukabhs: Start again: https://github.com/ab77/netflix-proxy

You are using some pretty old instructions and the commands you are using are also completely wrong.

**Comment by abukabhs** [comment] 2016-03-25 12:36
I am getting US netflix working though!

**Comment by ab77** [comment] 2016-03-25 12:40
@abukabhs: good for you.

try:
```
sudo iptables -D FRIENDS -s x.x.x.x/32 -j ACCEPT && \
  (sudo iptables-save > /etc/iptables/rules.v4 || sudo iptables-save > /etc/iptables.rules)
```

**Comment by ab77** [comment] 2016-03-25 14:15
OK, I fixed the major issue, which was affecting most people. Basically, IPv6 was broken in most cases.

Please rebuild with the new version and it should be good to go

(no need to destroy the tunnel, use the current configuration - jut rebuild the VPS).

**Comment by ab77** [comment] 2016-03-25 14:22
(also, re-read the instructions, there is an extra step without which it will fail)

**Comment by nixxle** [comment] 2016-03-25 19:43
Yes! It works! :) Thanks, I donated a beer through Paypal, cheers.

**Comment by abukabhs** [comment] 2016-03-25 20:16
Authorizing Additional IPs
how to reset the password?
which file has the credentials?

**Comment by scottaki** [comment] 2016-03-26 03:39
Ugh... I'm still struggling for some reason. Same issue, even with the new -s option for build.sh... New droplets and everything. Just not having any luck! At least @nixxle proved that the system works again!

**Comment by abukabhs** [comment] 2016-03-26 08:57
Netflix was working fine with the old instructions.
With the new one I created the tunnel and I ran the command:
ifup he-ipv6 && git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh -s 2001:470:1f07:8a6::

I received the following:
; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> +time=10 netflix.com @192.241.174.178
;; global options: +cmd
;; connection timed out; no servers could be reached
Failure! Retrying in 160..
You've failed me for the last time! (/usr/bin/dig +time=10 netflix.com @192.241.174.178
; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> +time=10 netflix.com @192.241.174.178
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by ab77** [comment] 2016-03-26 09:13
Build command wrong - you are missing the subnet prefix (e.g. `./build.sh -s 2001:470:1f07:8a6::/64`).

**Comment by ab77** [comment] 2016-03-26 09:16
To change the password, see https://github.com/ab77/netflix-proxy/wiki/Changing-Admin-Password-For-Auth-Version.

You can work everything else out from that and this: https://github.com/ab77/netflix-proxy/issues/114#issuecomment-201742433

**Comment by ab77** [comment] 2016-03-26 09:16
@scottaki: did you get it working?

**Comment by scottaki** [comment] 2016-03-26 09:22
@ab77... no, unfortunately no luck for me... everything seems to build and test OK, but actually trying to play a title on Netflix just results in "internet connection problem", with lots of error 420s when looking at the web inspector. Everything else loads OK. Ping6 and Traceroute6 give the right results. Weird...

Any chance you could take a quick look for me? Same login details as last time – just added your key back in.

**Comment by abukabhs** [comment] 2016-03-26 09:49
I have rebuilt my droplet several times already and I put the command with
/64 and it didn't work.  I will try one more time. I will also try my luck
with vultr.
Thanks

**Comment by machcnz** [comment] 2016-03-26 09:59
I've noted that the android app will throw a network error if blocking google/hardcoded DNS - be sure to redirect rather than drop DNS.

**Comment by ab77** [comment] 2016-03-26 10:26
@machcnz: very interesting, thanks for pointing this out.

**Comment by ab77** [comment] 2016-03-26 10:59
@scottaki: something is wrong with the IPv6 path between your VPS and Netflix CDNs. Try blowing that one away entirely and deploy a new one, in a different DC (doesn't really matter which one). After you build the proxy, first try:

`docker run -it --rm ubuntu bash -c "ifconfig && ping6 -c 10 ipv6_1-lagg0-c102.1.iad001.ix.nflxvideo.net"`

If you get a reply, then it is working and you should proceed with the build, otherwise there is a communication issue between HE and Netflix, which could be caused by weird MTU mis-matches. You can try playing around with MTU size under the Advanced tab of the HE tunnel setting, but it is easier just to find a DC with a path to Netflix over IPv6 which works..

**Comment by abukabhs** [comment] 2016-03-26 10:59
I changed from DigitalOcean to Vultr and Netflix is working now.

However http://<ipaddr>:8080/ didn't accept my user name and password.
I tried the procedure:
 https://github.com/ab77/netflix-proxy/wiki/Changing-Admin-Password-For-Auth-Version.

but I get
Error: near "sqlite": syntax error

**Comment by ab77** [comment] 2016-03-26 11:01
@abukabhs: Google is your friend here and also #netflix-proxy IRC channel :)

Good luck!

**Comment by scottaki** [comment] 2016-03-26 11:16
Thanks @ab77. I'll keep working on it and see how things go. Appreciate the help!

**Comment by abukabhs** [comment] 2016-03-26 11:28
I managed to change the password!

Do you have plan to automate ip address addition or deletion?
I need to run a cron script at my dd-wrt or open-wrt router to automatically change my ip address whenever my isp change my ip address.

**Comment by ab77** [comment] 2016-03-26 11:30
@abukabhs: automate away! :grimacing:  (and if you find a neat solution, perhaps you can every write a Wiki page?)

**Comment by scottaki** [comment] 2016-03-26 11:42
It works!! @ab77 you genius! Seems like it was something to do with both of the DCs I was using. Tried somewhere else and it now works perfectly! Amazing!!

**Comment by ab77** [comment] 2016-03-26 11:44
Good stuff, I am going to close this before the thread gets hijacked :grimacing:

**Closed by ab77** 2016-03-26 11:44 UTC

**Comment by abukabhs** [comment] 2016-03-26 16:11
Seeing the complexity of what you have developed so far, I would think that
automation should be quite easy for you.

Please keep us updated with your future fixes and improvements.

Thanks a lot for your support.

On Sat, Mar 26, 2016 at 2:30 PM, Anton Belodedenko <notifications@github.com

**Comment by abukabhs** [comment] 2016-04-01 11:01
Hello
Would you consider supporting the use of no-ip to spare users from manually
updating their ips?
Thanks
