### ISSUE TITLE
Amazon EC2 - Stuck at  "testing DNS"

### ISSUE THREAD

**Issue by andresmorago** [ab77/netflix-proxy#213] opened 2016-10-15 00:00 UTC
Hello

My new installation is failing during the process. I have a fresh EC2 instance and installation gets stuck at the end.
Server becomes unresponsive and i have to restart mu SSH session

```
ubuntu@ip-172-31-55-79:/opt/netflix-proxy$ sudo ./build.sh -c 181.56.yyy.xxx
resolved params: clientip=181.56.146.156 ipaddr=172.31.55.79 extip=54.164.163.162
cmd: ./build.sh -r=1 -b=0 -s= -z=0 -n=1 -u= -p [secret] -k [secret]

 * enabling DNS recursion...                                                                                                                                                                                [ OK ]
 * authorising clientip=181.56.146.156 on iface=eth0...                                                                                                                                                     [ OK ]
 * adding IPv4 iptables rules...                                                                                                                                                                            [ OK ]
 * creating Docker and sniproxy configuration templates...                                                                                                                                                  [ OK ]
 * checking IPv6 connectivity...                                                                                                                                                                            [fail]
 * configuring sniproxy and Docker...                                                                                                                                                                       [ OK ]
 * installing iptables|netfilter-persistent service...                                                                                                                                                      [ OK ]
 * socialising Docker with iptables-persistent service...                                                                                                                                                   [ OK ]
 * updating iptables-persistent init script...                                                                                                                                                              [ OK ]
 * saving iptables rules...                                                                                                                                                                                 [ OK ]
 * creating zones.override from template...                                                                                                                                                                 [ OK ]
 * updating db.override with extip=54.164.163.162 and date=20161014...                                                                                                                                      [ OK ]
 * installing python-pip and docker-compose...                                                                                                                                                              [ OK ]
 * configuring netflix-proxy-admin backend...                                                                                                                                                               [ OK ]
 * configuring netflix-proxy-admin reverse-proxy...                                                                                                                                                         [ OK ]
 * creating and starting Docker containers...                                                                                                                                                               [ OK ]
 * configuring upstart...                                                                                                                                                                                   [ OK ]
 * reloading ipables rules...                                                                                                                                                                               [ OK ]
 * no specific steps to execute for Ubuntu at this time...                                                                                                                                                  [ OK ]
 * testing DNS...


```

**Comment by ab77** [comment] 2016-10-15 11:42
Try commenting out all the `iptables` stuff in the build script. It doesn't work with EC2's security groups. i used to have a `-i` switch to disable any addition of `iptables` rules during build, but since v2, this has not been possible.

**Comment by andresmorago** [comment] 2016-10-15 23:45
thanks. testing right now.
with this new version, is it possible to re-install it over the first installation instead of getting  fresh news EC2 instance?

**Comment by andresmorago** [comment] 2016-10-19 15:14
hello .
im noticing that there is no port 53 being opened on my instance. I already set up the security group for TCP/UDP 53 but no open port is being shown from my side.

**Comment by ab77** [comment] 2016-10-20 09:31
Is the `bind` container running?

**Comment by andresmorago** [comment] 2016-10-20 20:26
yes. it is
```
ubuntu@ip-172-31-55-157:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                            NAMES
372407f9e566        ab77/bind           "/usr/sbin/named -c /"   4 days ago          Up 4 days           0.0.0.0:53->53/udp                                               bind
326fffa42766        andyshinn/dnsmasq   "dnsmasq -k --port=53"   4 days ago          Up 4 days           53/tcp, 53/udp, 0.0.0.0:5353->5353/tcp, 0.0.0.0:5353->5353/udp   dnsmasq
3c8a4b5bf382        andyshinn/dnsmasq   "dnsmasq -k --log-fac"   4 days ago          Up 4 days           53/tcp, 53/udp                                                   caching-resolver
3b29781dd1b1        abiosoft/caddy      "/usr/bin/caddy --con"   4 days ago          Up 4 days                                                                            caddy
468a246d74fd        ab77/sniproxy       "/bin/sh -c /opt/snip"   4 days ago          Up 4 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                         sniproxy
ubuntu@ip-172-31-55-157:~$
```

**Comment by ab77** [comment] 2016-10-20 20:29
Check `netflix-proxy.log` and try to do the same things as failing in there locally with `dig` to see where the problem is.

**Comment by andresmorago** [comment] 2016-10-20 22:20
hello ab77
i think i have made some progress. i already configured my instance and when i go to ipinfo.io it will show the netflix-proxy admin site. i type the password and authorize my ip address. i then flush my dns from windows and try again to go to ipinfo.io but it will take me again to the same admin site

**Comment by ab77** [comment] 2016-10-21 06:12
Try closing all the browser windows and cleaning up browser processes on top of DNS flush.

**Closed** 2016-12-05 14:02 UTC
